"""Deterministic manifests for portable client report bundles.

The manifest is deliberately a small, boring contract.  It is generated from
bytes already present in the bundle and never reaches out to a provider or the
network.  A manifest therefore remains useful after a bundle is copied away
from the application workspace.
"""

from __future__ import annotations

import hashlib
import json
import mimetypes
from pathlib import Path, PurePosixPath
from typing import Any, Iterable


class ReportManifestService:
    """Create and verify content-addressed bundle manifests."""

    MANIFEST_VERSION = "report-manifest.v1"

    @staticmethod
    def canonical_bytes(payload: Any) -> bytes:
        return json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")

    @staticmethod
    def sha256_bytes(value: bytes) -> str:
        return hashlib.sha256(value).hexdigest()

    @classmethod
    def file_entry(cls, root: Path, relative_path: str, *, role: str | None = None) -> dict[str, Any]:
        path = cls._safe_path(root, relative_path)
        data = path.read_bytes()
        entry: dict[str, Any] = {
            "path": PurePosixPath(relative_path).as_posix(),
            "sha256": cls.sha256_bytes(data),
            "bytes": len(data),
            "mime_type": mimetypes.guess_type(path.name)[0] or "application/octet-stream",
        }
        if role:
            entry["role"] = role
        return entry

    @classmethod
    def build_manifest(
        cls,
        *,
        bundle_id: str,
        snapshot: Any,
        files: Iterable[dict[str, Any]],
        theme_version: str,
        renderer_version: str,
        claims: Iterable[dict[str, Any]] = (),
        assets: Iterable[dict[str, Any]] = (),
        assessment: dict[str, Any] | None = None,
        pdf_renderer: str = "minimal-pdf-fallback",
    ) -> dict[str, Any]:
        """Return a stable manifest; ``created_at`` comes from the snapshot."""
        snapshot_dict = snapshot.to_dict() if hasattr(snapshot, "to_dict") else dict(snapshot)
        manifest: dict[str, Any] = {
            "manifest_version": cls.MANIFEST_VERSION,
            "bundle_id": bundle_id,
            "report_snapshot_id": snapshot_dict.get("id"),
            "run_id": snapshot_dict.get("run_id"),
            "report_contract": snapshot_dict.get("report_contract"),
            "schema_version": snapshot_dict.get("schema_version"),
            "renderer_version": renderer_version,
            "theme_version": theme_version,
            "created_at": snapshot_dict.get("created_at"),
            "source_snapshot_ids": dict(sorted((snapshot_dict.get("source_snapshot_ids") or {}).items())),
            "source_hashes": dict(sorted((snapshot_dict.get("source_hashes") or {}).items())),
            "payload_sha256": snapshot_dict.get("payload_sha256"),
            "completeness_percent": snapshot_dict.get("completeness_percent", 0),
            "status": snapshot_dict.get("status", "limited"),
            "pdf_renderer": pdf_renderer,
            "model_disclosure": {
                "agentic_analysis": "optional; only validated customer-safe findings are rendered",
                "deterministic_scores": "source snapshot values; never generated by a model",
            },
            "assessment": assessment or {
                "status": "unknown",
                "customer_safe_findings": 0,
                "disclosure": "No validated customer-safe agentic assessment was available.",
            },
            "claims": sorted((dict(item) for item in claims), key=lambda item: str(item.get("id", ""))),
            "assets": sorted((dict(item) for item in assets), key=lambda item: str(item.get("path", ""))),
            "files": sorted((dict(item) for item in files), key=lambda item: str(item.get("path", ""))),
            "limitations": [
                "This bundle is an offline rendering of immutable evidence.",
                "Unknown, incomplete, or review-required evidence is shown as unknown.",
            ],
        }
        return manifest

    @classmethod
    def write_manifest(cls, bundle_dir: str | Path, manifest: dict[str, Any]) -> tuple[Path, str]:
        root = Path(bundle_dir)
        root.mkdir(parents=True, exist_ok=True)
        path = root / "manifest.json"
        data = json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=False).encode("utf-8") + b"\n"
        path.write_bytes(data)
        return path, cls.sha256_bytes(data)

    @classmethod
    def write_hashes(cls, bundle_dir: str | Path, entries: Iterable[dict[str, Any]]) -> Path:
        root = Path(bundle_dir)
        lines = [f"{item['sha256']}  {PurePosixPath(str(item['path'])).as_posix()}" for item in entries]
        path = root / "hashes.sha256"
        path.write_text("\n".join(sorted(lines)) + "\n", encoding="utf-8")
        return path

    @classmethod
    def validate_manifest(cls, bundle_dir: str | Path, manifest: dict[str, Any]) -> dict[str, Any]:
        root = Path(bundle_dir)
        snapshot_id = manifest.get("report_snapshot_id")
        payload_hash = manifest.get("payload_sha256")
        checked = 0
        for item in manifest.get("files", []):
            path = cls._safe_path(root, str(item.get("path", "")))
            if not path.is_file():
                raise ValueError(f"manifest file is missing: {item.get('path')}")
            actual = cls.sha256_bytes(path.read_bytes())
            if actual != item.get("sha256"):
                raise ValueError(f"manifest hash mismatch: {item.get('path')}")
            if path.stat().st_size != item.get("bytes"):
                raise ValueError(f"manifest size mismatch: {item.get('path')}")
            checked += 1
        for asset in manifest.get("assets", []):
            path = cls._safe_path(root, str(asset.get("path", "")))
            if not path.is_file():
                raise ValueError(f"manifest asset is missing: {asset.get('path')}")
            if cls.sha256_bytes(path.read_bytes()) != asset.get("sha256"):
                raise ValueError(f"manifest asset hash mismatch: {asset.get('path')}")
        evidence_assets = {
            str(asset.get("evidence_ref"))
            for asset in manifest.get("assets", [])
            if asset.get("evidence_ref")
        }
        for claim in manifest.get("claims", []):
            if (
                claim.get("source_snapshot_id") != snapshot_id
                or claim.get("source_hash") != payload_hash
            ):
                raise ValueError(f"manifest claim source mismatch: {claim.get('id')}")
            if claim.get("kind") == "validated_assessment":
                refs = claim.get("evidence_refs")
                if not isinstance(refs, list) or not refs:
                    raise ValueError(f"validated claim lacks evidence: {claim.get('id')}")
                if any(str(ref.get("artifact_path")) not in evidence_assets for ref in refs):
                    raise ValueError(f"validated claim evidence is not portable: {claim.get('id')}")
        return {"valid": True, "checked_files": checked, "manifest_version": manifest.get("manifest_version")}

    @staticmethod
    def _safe_path(root: Path, relative_path: str) -> Path:
        if not relative_path or PurePosixPath(relative_path).is_absolute() or ".." in PurePosixPath(relative_path).parts:
            raise ValueError("bundle paths must be relative and contained")
        path = (root / Path(*PurePosixPath(relative_path).parts)).resolve()
        if path != root.resolve() and root.resolve() not in path.parents:
            raise ValueError("bundle path escapes bundle root")
        return path
