"""P56 T5: the authoring kit's RECIPES - name a beat, get the proven combination as data the author BINDS.

`recipes.py` reads only the generated layer, returns candidates and allocates nothing. The pins: the badge
ladder's own measured shape (its two dials, its first member at +0.0), the option defaults handed over as COPIES,
`binds` naming what the author owes per member off the member CARD's axis, an unknown and an ambiguous name both
raising with what they found, a `candidate` flagged with the reason it has no proof, and `for_act`'s order.

Everything but the badge ladder's dials runs on a TMP catalogue: the real layer is regenerated by other lanes (new
cards, re-membered recipes), so a test pinning another recipe's member list would fail on someone else's work.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "content/video_engine/scripts"))

from authoring import effects as E  # noqa: E402
from authoring import recipes as RX  # noqa: E402

BADGE = "recipe:badge-ladder"
BADGE_DIALS = {"FIRST_BADGE_S": 2.05, "BADGE_GAP_S": 1.3}
NEED_WORDS = {"asset", "data", "target", "label", "builder args"}


# ---------------------------------------------------------------- a tmp catalogue (the layer's shape, not its content)
def _card(cid: str, check: str, key: str = "", axis: str | None = None, token: str | None = None) -> dict:
    return {"id": cid, "axis": axis or cid.split(":")[0], "token": token or cid.split(":")[1],
            "title": f"The {cid} card", "aliases": [], "author": {"check": check, "key": key}}


def _member(card: str, offset_s: float | list = 0.0, **extra) -> dict:
    m = {"card": card, "option": None, "offset_s": offset_s, "role": "what this member does in the combination",
         "options": None, "optional": None, "title": f"The {card} card"}
    m.update(extra)
    return m


def _recipe(rid: str, title: str, members: list[dict], acts=("EXPLAINS",), status: str = "proven",
            count: int = 1, **extra) -> dict:
    rec = {"id": rid, "axis": "recipe", "title": title, "aliases": [], "acts": list(acts), "members": members,
           "window_s": 6.0, "dials": {}, "does": f"{title} does one thing.", "status": status, "count": count,
           "proof": ({"project": "a-project", "build": "a-build", "timeline": "t.timeline.json", "t": 1.5,
                      "members_at": [1.5]} if status == "proven" else None)}
    rec.update(extra)
    return rec


def _layer(tmp_path: Path, records: list[dict]) -> Path:
    (tmp_path / "docs").mkdir(parents=True, exist_ok=True)
    (tmp_path / "docs/EFFECTS-CATALOG.jsonl").write_text(
        "\n".join(json.dumps(r) for r in records) + "\n", encoding="utf-8")
    return tmp_path


# ---------------------------------------------------------------- the generated layer, filtered to the recipes
def test_load_reads_the_recipes_of_the_generated_layer_and_nothing_else():
    recipes = RX.load()
    assert recipes and all(r["axis"] == "recipe" and r["members"] for r in recipes)
    assert len(recipes) == sum(1 for r in E.load() if E.is_recipe(r))


def test_load_reads_a_tmp_layer_when_one_is_named(tmp_path):
    repo = _layer(tmp_path, [_card("exit:wipe", "exit"), _recipe("recipe:x", "The x", [_member("exit:wipe")])])
    assert [r["id"] for r in RX.load(repo)] == ["recipe:x"]


# ---------------------------------------------------------------- the badge ladder: the one measured pin (P56 T4)
def test_the_badge_ladder_returns_its_members_in_order_with_its_two_dials():
    p = RX.preset("the badge ladder")
    assert p["id"] == BADGE and p["status"] == "proven" and p["candidate_reason"] is None
    assert len(p["members"]) >= 2 and p["members"][0]["offset_s"] == 0.0
    offsets = [m["offset_s"] for m in p["members"]]
    assert offsets == sorted(offsets), offsets
    assert p["dials"] == BADGE_DIALS
    assert p["proof"]["project"] and p["proof"]["build"] and p["proof"]["t"] >= 0
    assert p["count"] >= 1 and p["acts"] and p["window_s"]


@pytest.mark.parametrize("spelling", [BADGE, "badge ladder", "The Badge Ladder", "badge-ladder"])
def test_the_id_the_title_and_the_spellings_all_resolve(spelling):
    assert RX.preset(spelling)["id"] == BADGE


def test_every_member_of_the_badge_ladder_carries_a_need():
    p = RX.preset("the badge ladder")
    assert len(p["binds"]) == len(p["members"])
    for i, bind in enumerate(p["binds"]):
        assert bind["member"] == i and bind["card"] == p["members"][i]["card"]
        # the card member needs the asset; each badge member (`dock_option:badge`, carded 2026-09-13) needs its TEXT
        assert bind["needs"] == (["asset"] if i == 0 else ["label"]), bind


def test_every_need_in_the_real_catalogue_is_a_word_from_the_table():
    for recipe in RX.load():
        p = RX.preset(recipe["id"])
        assert [b["member"] for b in p["binds"]] == list(range(len(p["members"]))), recipe["id"]
        for bind in p["binds"]:
            assert set(bind["needs"]) <= NEED_WORDS, (recipe["id"], bind)


# ---------------------------------------------------------------- the option defaults are a COPY, never the record
def test_the_preset_is_data_the_author_may_edit_without_touching_the_record(tmp_path):
    repo = _layer(tmp_path, [
        _card("species:trace", "species"),
        _recipe("recipe:copy", "The copy", [_member("species:trace", 0.0, options={"draw_s": 0.55, "bow": 0.16}),
                                            _member("species:trace", [1.0, 2.0])], dials={"BEAT_S": 1.26}),
    ])
    records = E.load(repo)              # the hazard: a caller holding the layer and presetting twice off it
    p = RX.preset("the copy", records=records)
    p["members"][0]["options"]["draw_s"] = 99.0
    p["members"][1]["offset_s"][0] = 99.0
    p["dials"]["BEAT_S"] = 99.0
    p["members"].append("junk")
    p["binds"].clear()
    for again in (RX.preset("the copy", records=records), RX.preset("the copy", repo)):
        assert again["members"][0]["options"] == {"draw_s": 0.55, "bow": 0.16}
        assert again["members"][1]["offset_s"] == [1.0, 2.0]
        assert again["dials"] == {"BEAT_S": 1.26} and len(again["members"]) == 2 and len(again["binds"]) == 2
    assert records[1]["members"][0]["options"] == {"draw_s": 0.55, "bow": 0.16}   # the record itself, untouched


# ---------------------------------------------------------------- the binds table, read off the member card's axis
@pytest.mark.parametrize("card, needs", [
    (_card("dock_kind:image", "dock", "dock tuple (asset_id, slot, enter, exit[, opts])"), ["asset"]),
    (_card("dock_payload:chart", "dock", "a `<asset>.series.json` beside the dock's asset"), ["asset", "data"]),
    (_card("dock_option:read", "dock_option", "dock option {'centre': True, 'read': {centre_w, centre_x}}"),
     ["asset", "target"]),
    (_card("dock_option:centre", "dock_option", "dock option {'centre': True}"), ["asset"]),
    (_card("page_builder:bars", "chart", "ledger plate id ledger:<series-id>:bars"), ["data", "builder args"]),
    (_card("chart_dock:series", "chart", "`series: [...]` in the dock asset's .series.json"), ["data", "builder args"]),
    (_card("species:callout", "species", 'species[] {"kind": "callout", "at", "dur", "target"}'),
     ["target", "label"]),
    (_card("species:trace", "species", "species[] {\"kind\": \"trace\"}"), ["target"]),
    (_card("page_species:figure", "species", "species[] on a ledger row"), ["target", "label"]),
    (_card("plate_option:ken", "plate", "plate id suffix `;ken=`"), ["asset"]),
    (_card("exit:wipe", "exit", "shot row 6th element 'wipe'"), []),
    (_card("page_enter:snap", "enter", "the ledger id's enter field"), []),
    (_card("idle:drift", "idle", "`;idle=drift`"), []),
    (_card("kinetics:ken", "module", "a kinetics module"), []),
])
def test_the_binds_table_derives_the_need_from_the_member_card(tmp_path, card, needs):
    repo = _layer(tmp_path, [card, _recipe("recipe:t", "The t", [_member(card["id"]), _member(card["id"], 1.0)])])
    assert [b["needs"] for b in RX.preset("recipe:t", repo)["binds"]] == [needs, needs]


def test_a_member_whose_card_is_not_in_the_catalogue_says_so_instead_of_going_quiet(tmp_path):
    repo = _layer(tmp_path, [_card("exit:wipe", "exit"),
                             _recipe("recipe:t", "The t", [_member("exit:wipe"), _member("dock_kind:ghost", 1.0)])])
    needs = RX.preset("recipe:t", repo)["binds"][1]["needs"]
    assert len(needs) == 1 and "dock_kind:ghost" in needs[0] and "build_effects_catalog.py" in needs[0]


# ---------------------------------------------------------------- a candidate carries the reason it has no proof
def test_a_candidate_returns_flagged_with_the_reason_it_has_no_proof(tmp_path):
    repo = _layer(tmp_path, [_card("species:steam", "species"),
                             _recipe("recipe:maybe", "The maybe", [_member("species:steam"), _member("species:steam", 1.0)],
                                     status="candidate", count=0)])
    p = RX.preset("the maybe", repo)
    assert p["status"] == "candidate" and p["proof"] is None
    assert p["candidate_reason"] == RX.CANDIDATE_REASON == "no approved cut has carried it (no proof)"


# ---------------------------------------------------------------- the two refusals
def test_an_unknown_name_raises_naming_the_nearest_titles():
    with pytest.raises(LookupError) as err:
        RX.preset("qqzzx flarp")
    msg = str(err.value)
    assert "is not a recipe" in msg and "nearest titles" in msg
    assert len(re.findall(r"^\s+- recipe:", msg, flags=re.M)) == 3


def test_a_card_is_not_a_recipe_and_the_refusal_names_recipes_only():
    with pytest.raises(LookupError) as err:
        RX.preset("evidence wall")
    assert "recipe:" in str(err.value) and "dock_payload:stack" not in str(err.value)


def test_an_ambiguous_name_raises_naming_every_candidate(tmp_path):
    repo = _layer(tmp_path, [
        _card("exit:wipe", "exit"),
        _recipe("recipe:alpha-ladder", "The alpha ladder", [_member("exit:wipe"), _member("exit:wipe", 1.0)]),
        _recipe("recipe:beta-ladder", "The beta ladder", [_member("exit:wipe"), _member("exit:wipe", 1.0)]),
    ])
    with pytest.raises(LookupError) as err:
        RX.preset("ladder", repo)
    msg = str(err.value)
    assert "ambiguous" in msg and "2 recipes match" in msg
    assert "recipe:alpha-ladder" in msg and "recipe:beta-ladder" in msg


# ---------------------------------------------------------------- for_act: proven first, then count, then id
def test_for_act_puts_the_proven_first_then_the_count_then_the_id(tmp_path):
    two = [_member("exit:wipe"), _member("exit:wipe", 1.0)]
    repo = _layer(tmp_path, [_card("exit:wipe", "exit"),
                             _recipe("recipe:z-often", "Z often", two, count=9),
                             _recipe("recipe:a-once", "A once", two, count=1),
                             _recipe("recipe:b-once", "B once", two, count=1),
                             _recipe("recipe:c-candidate", "C candidate", two, status="candidate", count=0),
                             _recipe("recipe:other-act", "Other act", two, acts=("RANKS",), count=99)])
    assert [p["id"] for p in RX.for_act("EXPLAINS", repo)] == [
        "recipe:z-often", "recipe:a-once", "recipe:b-once", "recipe:c-candidate"]
    assert [p["id"] for p in RX.for_act("RANKS", repo)] == ["recipe:other-act"]
    assert RX.for_act("QUOTES", repo) == []


def test_for_act_hands_back_presets_with_their_binds(tmp_path):
    repo = _layer(tmp_path, [_card("dock_kind:image", "dock"),
                             _recipe("recipe:t", "The t", [_member("dock_kind:image"), _member("dock_kind:image", 2.05)])])
    p = RX.for_act("EXPLAINS", repo)[0]
    assert p["binds"] == [{"member": 0, "card": "dock_kind:image", "needs": ["asset"]},
                          {"member": 1, "card": "dock_kind:image", "needs": ["asset"]}]


def test_for_act_reads_the_real_layer_and_every_recipe_it_names_carries_that_act():
    for act in {a for r in RX.load() for a in r["acts"]}:
        got = RX.for_act(act)
        assert got and all(act in p["acts"] for p in got), act
        assert [p["status"] != "proven" for p in got] == sorted(p["status"] != "proven" for p in got), act


# ---------------------------------------------------------------- the kit's rule: nothing here names an episode
def test_the_kit_module_names_no_episode():
    names = {p.name for p in (ROOT / "content/video_engine/projects").glob("*/*") if p.is_dir()}
    src = (ROOT / "content/video_engine/scripts/authoring/recipes.py").read_text(encoding="utf-8").lower()
    hits = sorted(n for n in names if re.search(rf"(?<![\w-]){re.escape(n.lower())}(?![\w-])", src))
    assert names and hits == []


def test_the_module_refuses_to_be_an_allocator_in_writing():
    doc = " ".join((RX.__doc__ or "").split())
    for phrase in ["NOT AN ALLOCATOR", "names no episode", "chooses nothing by count", "writes no shot table",
                   "the AUTHOR binds", "There is no allocator"]:
        assert phrase in doc, phrase
