"""Generated by build_assembly.py; source rows are hard cuts over real video clips."""
# Do not edit by hand; regenerate from production/edit.json.
W = [(0.0, 6.6, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v7/build/clips/hook.mp4', (0, 0, 0), [], 'cut', []),
     (6.6, 8.033332999999999, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v7/build/clips/news.mp4', (0, 0, 0), [], 'cut', []),
     (8.033333, 11.100000000000001, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v7/build/clips/follow-up.mp4', (0, 0, 0), [], 'cut', []),
     (11.1, 12.4, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v7/build/clips/replay-hold.mp4', (0, 0, 0), [], 'cut', []),
     (12.4, 13.6, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v7/build/clips/anime.mp4', (0, 0, 0), [], 'cut', []),
     (13.6, 17.3, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v7/build/clips/impact-head-snap-v4.mp4', (0, 0, 0), [], 'cut', []),
     (17.3, 21.5, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v7/build/clips/hendo.mp4', (0, 0, 0), [], 'cut', []),
     (21.5, 24.1, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v7/build/clips/hendo-replay.mp4', (0, 0, 0), [], 'cut', [])]
