"""Generated by build_assembly.py; source rows are hard cuts over real video clips."""
# Do not edit by hand; regenerate from production/edit.json.
W = [(0.0, 3.5, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly/build/clips/hook.mp4', (0, 0, 0), [], 'cut', []),
     (3.5, 8.1, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly/build/clips/news.mp4', (0, 0, 0), [], 'cut', []),
     (8.1, 11.6, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly/build/clips/knockout.mp4', (0, 0, 0), [], 'cut', []),
     (11.6, 12.9, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly/build/clips/replay-hold.mp4', (0, 0, 0), [], 'cut', []),
     (12.9, 14.1, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly/build/clips/anime.mp4', (0, 0, 0), [], 'cut', []),
     (14.1, 14.799999999999999, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly/build/clips/impact.mp4', (0, 0, 0), [], 'cut', []),
     (14.8, 17.8, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly/build/clips/brain.mp4', (0, 0, 0), [], 'cut', []),
     (17.8, 22.0, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly/build/clips/hendo.mp4', (0, 0, 0), [], 'cut', []),
     (22.0, 24.6, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly/build/clips/hendo-replay.mp4', (0, 0, 0), [], 'cut', [])]
