"""The Markdown face of the animation registry - `docs/ANIMATION-REGISTRY.md`.

Split out of `build_animation_registry.py` on 2026-09-05, when the citation-chain and provenance
rules pushed that module past the 800-line style cap. The build stays there; the recipe and the
rendering live here. `RECIPE` is the generated file's own header, so the artifact carries the whole
of how it was made - `--check` fails when the file drifts from it.

The ordering constants are defined here because the Markdown is what orders the registry for a
reader; `build_animation_registry` imports them so there is exactly one definition.
"""
from __future__ import annotations

KIND_ORDER = {"code": 0, "dial": 1, "formula": 2}
STATUS_ORDER = ("implemented", "tracked", "retired", "orphaned")
PROVENANCE_ORDER = ("sourced", "derived", "unsourced")


def cite_text(cites: list[dict]) -> str:
    return ", ".join(c["ref"] + (f" -> {c['to']}" if c["to"] else "") for c in cites)


def evidence_md(rec: dict) -> str:
    return " — " + ", ".join(rec["status_evidence"]) if rec["status_evidence"] else " — (no evidence)"


def code_md(records: list[dict]) -> list[str]:
    out = ["## Code (kinetics)", ""]
    code = [r for r in records if r["kind"] == "code"]
    for module in sorted({r["module"] for r in code}):
        out += [f"### `{module}`", ""]
        for rec in [r for r in code if r["module"] == module]:
            flag = f"flag `{rec['flag']}`" if rec["flag"] else "no flag"
            facts = f"{flag} · {rec['template_sites']} template site(s) · {len(rec['tests'])} test(s)"
            out.append(f"- **{rec['name']}** — `{rec['signature']}` — {rec['module']}:{rec['line']}"
                       f" — {facts} — {rec['status']}{evidence_md(rec)}")
        out.append("")
    return out


def dial_md(records: list[dict]) -> list[str]:
    out = ["## Dials", ""]
    dials = [r for r in records if r["kind"] == "dial"]
    for path in sorted({r["path"] for r in dials}):
        out += [f"### `{path}`", ""]
        for rec in [r for r in dials if r["path"] == path]:
            cites = f" — {cite_text(rec['cites'])}" if rec["cites"] else ""
            out.append(f"- **{rec['name']}** — `{rec['value']}` — {rec['path']}:{rec['line']}{cites}")
        out.append("")
    return out


def formula_line(rec: dict) -> str:
    return (f"- **{rec['name']}** — {rec['expr']} — {rec['path']}:{rec['line']}"
            f" — {rec['provenance']}{evidence_md(rec)}")


def formula_md(records: list[dict]) -> list[str]:
    formulas = [r for r in records if r["kind"] == "formula"]
    out = ["## Formulas and laws", ""]
    for status in STATUS_ORDER:
        rows = [r for r in formulas if r["status"] == status]
        out += [f"### {status} ({len(rows)})", ""] + [formula_line(r) for r in rows] + [""]
    orphans = [r for r in formulas if r["status"] == "orphaned"]
    out += [f"## Orphaned ({len(orphans)})", "",
            "Stated in the docs, implemented nowhere, tracked by no BACKLOG or doc-47 row, retired by",
            "nobody. This is the list to triage. Note that",
            "`content/video_engine/sources/reference_analyses/complete_research_evidence_bundle/`",
            "holds byte-identical copies of three of the scanned research files, so a research orphan",
            "usually appears twice, once per path.", ""]
    return out + [formula_line(r) for r in orphans] + [""]


RECIPE = """# Animation registry — every formula, dial and kinetics symbol, with its status

Generated by `python content/video_engine/scripts/build_animation_registry.py --write`. Never
hand-edited: the recipe below is the whole of it, and `--check` fails when this file drifts from it.

**{code} code · {dial} dial · {formula} formula records — {status}.**
**Provenance of the formula records — {provenance}.**

**Read** — code: `content/video_engine/scripts/kinetics/*.mjs` (every `export const|function`, plus
every key of an exported constant object). Dials: those same constant objects, and the player
template's `MARK` / `SP` / `LP` / `MOUNT_STEPS` / `DISSOLVE_S` / `LP_MOUNT_RISE` / `CAP_LAST_HOLD_S`.
Formulas: `docs/content-video-engine/{{29,42..53}}-*.md`, `FINDING-the-animation-math-*.md`,
`briefs/ANSWERS-RESEARCH-BRIEF-animation-craft.md`, and the `reference_analyses` files named
ANIMATION / DRAWING / KINETIC / academic_literature — every `$$` block, every `=` line carrying a
mathematical symbol, every line naming a law. Chain roots also read the headers, comments and rule
constants of `content/video_engine/scripts/gate_*.py`.

**Status** — precedence implemented > retired > tracked > orphaned.
*implemented*: a kinetics module cites the formula's section, or the name is written in a module or
the template (code: the player calls it, a test names it, or another kinetics line uses it), or the
citation chain below reaches it. *retired*: a BACKLOG or doc-47 row naming it says reclassified /
withdrawn / closed / invented **in its status text** (`closed-form` is not `closed`, and the word
inside a bolded title is a title, not a verdict). *tracked*: such a row names it, or cites its
section in `docs/DOCS-CITATIONS.jsonl`, or graduates it (`**CLOSED <date> by <doc>**` is a
graduation to a written standard, not a withdrawal — the target doc is the evidence).
*orphaned*: none of those — stated and unattached.

**The citation chain (depth 2)** — the kinetics modules cite our numbered doc sections (`42 s42.1`),
and those sections carry the research section the doc was extracted from. A research section reached
from an implemented code record — or from a gate's rule constant — through `code → our section →
research section` inherits *implemented*, with the chain as its evidence
(`…/stroke.mjs:5 → 42§42.1 → 07§1.2`). The second hop is read two ways: the ``07`` §5.3-style
references written in our section's body (a whole-doc cite reads the whole doc's body, so doc 45's
`06` §2–4 counts), and the disposition rows of `docs/content-video-engine/RESEARCH-INDEX.md`
(`| 1.2 Kinematic Arc-Length Reparameterization | EXTRACTED -> 42 SS42.1 |`). A reached section
covers its subsections. Without this a shipped law reads as an orphan on the research side, because
the module cites our doc and never the file the doc was extracted from.

**Provenance** (formula records) — *derived*: the section carries a `[DERIVED:` tag, or a BACKLOG /
doc-47 row naming it calls it invented, reclassified or derived. *sourced*: the record is itself in
`content/video_engine/sources/reference_analyses/`, or its section reaches such a file through the
chain above, or the section carries a `URL:`. *unsourced*: neither — a figure with nothing behind it.

**Named heuristics** — the template's `KINETICS:BEGIN..END` regions are `sync_kinetics.py`'s copies
of the modules, so uses inside them are not template use sites; a law is matched by its aliases and
anything else by the hyphen/slash compounds of its name (`Secondary-Motion`, `zero-slip`), never by
a common word; `zero-slip` and `FK/IK` were added to the law list because doc 48 states them as
rules; a kinetics constant key appears twice on purpose — as code surface (flag, sites, tests) and
as a dial (with its value); the research files are held twice on disk (a bundle copy and a top-level
copy), and a chain that reaches one reaches its byte-identical twin.
"""


def render_md(records: list[dict]) -> str:
    counts = {kind: sum(1 for r in records if r["kind"] == kind) for kind in KIND_ORDER}
    status = ", ".join(f"{sum(1 for r in records if r.get('status') == s)} {s}"
                       for s in STATUS_ORDER)
    provenance = ", ".join(f"{sum(1 for r in records if r.get('provenance') == p)} {p}"
                           for p in PROVENANCE_ORDER)
    head = RECIPE.format(status=status, provenance=provenance, **counts)
    return "\n".join([head] + code_md(records) + dial_md(records) + formula_md(records)) + "\n"
