from __future__ import annotations

from typing import Protocol

from src.models import DiscoveredAsset, InsightReport, InsightRun, PageRecord, RunStageEvent, SEOTarget, StageCheckpoint


class InsightRepository(Protocol):
    def upsert_target(self, target: SEOTarget) -> SEOTarget: ...

    def create_run(self, run: InsightRun) -> InsightRun: ...

    def update_run(self, run: InsightRun) -> InsightRun: ...

    def append_stage_event(self, event: RunStageEvent) -> RunStageEvent: ...

    def save_discovered_asset(self, asset: DiscoveredAsset) -> DiscoveredAsset: ...

    def save_page_record(self, page: PageRecord) -> PageRecord: ...

    def save_report(self, report: InsightReport) -> InsightReport: ...

    def save_checkpoint(self, checkpoint: StageCheckpoint) -> StageCheckpoint: ...

    def get_run(self, run_id: str) -> "InsightRun | None": ...
    def list_runs(self, limit: int = 20) -> list["InsightRun"]: ...
    def list_stage_events(self, run_id: str) -> list["RunStageEvent"]: ...
    def get_report(self, run_id: str, report_version: str) -> "InsightReport | None": ...
    def get_checkpoint(self, run_id: str, attempt_id: str, stage_name: str) -> "StageCheckpoint | None": ...
