from __future__ import annotations

from pathlib import Path
from typing import Protocol

from content.video_engine.src.models import VideoRun, VideoStageEvent


class VideoJobRepository(Protocol):
    @property
    def root(self) -> Path: ...

    def create_run(self, run: VideoRun) -> VideoRun: ...

    def update_run(self, run: VideoRun) -> VideoRun: ...

    def append_stage_event(self, event: VideoStageEvent) -> VideoStageEvent: ...

    def load_run(self, run_id: str) -> VideoRun | None: ...

    def list_runs(self) -> list[VideoRun]: ...

    def list_stage_events(self, run_id: str) -> list[VideoStageEvent]: ...

    def job_dir(self, run_id: str) -> Path: ...
