"""Memory trades the calendar short - AUTHORED shot table, timed from the take by build_short.py. Do not hand-edit; edit build_short.shot_table."""
W = [(0.0, 8.97, 'plate-customs;idle=drift;drift=35', (0.06, 6, -4), [('dock-b-calendar', 0, 1.56, 8.97, {'arrive': 'throw', 'mass': 'paper', 'centre': True, 'card_aspect': 1.8361})], 'dip', [{'kind': 'spotlight', 'at': 4.22, 'dur': 'hold', 'until': 6.28, 'target': {'kind': 'point', 'x': 0.2, 'y': 0.52}}, {'kind': 'spotlight', 'at': 6.28, 'dur': 'hold', 'until': 7.76, 'target': {'kind': 'point', 'x': 0.2, 'y': 0.82}}, {'kind': 'spotlight', 'at': 7.76, 'dur': 'hold', 'until': 8.97, 'target': {'kind': 'point', 'x': 0.8, 'y': 0.42}}]),
     (8.97, 14.78, 'ledger:ev-trade-the-calendar-v1:line:1:right:snap=dock-b-calendar:cut;idle=live', (0, 0, 0), [], 'dip', [{'kind': 'spotlight', 'at': 9.82, 'dur': 'hold', 'until': 15.28, 'target': {'kind': 'datum', 'index': 1, 'series': 0}}, {'kind': 'retitle', 'at': 11.82, 'dur': 1.4, 'text': 'They move around the print'}, {'kind': 'spotlight', 'at': 13.52, 'dur': 'hold', 'until': 14.78, 'target': {'kind': 'datum', 'index': 177, 'series': 1}}]),
     (14.78, 22.5, 'plate-desk;idle=drift;drift=35', (0.06, 6, -4), [], 'dip', [{'kind': 'spotlight', 'at': 15.86, 'dur': 'hold', 'until': 17.76, 'target': {'kind': 'point', 'x': 0.27, 'y': 0.645}}, {'kind': 'ticker', 'at': 17.76, 'dur': 4.64, 'target': {'kind': 'region', 'x0': 0.09, 'y0': 0.43, 'x1': 0.41, 'y1': 0.58}, 'density': 0.22, 'paper': '#16222E', 'tilt': 0}]),
     (22.5, 30.7, 'ledger:ev-into-vs-after-v1:bars:0:right:built:cut;idle=live', (0, 0, 0), [], 'cut', [{'kind': 'spotlight', 'at': 22.9, 'dur': 'hold', 'until': 26.16, 'target': {'kind': 'datum', 'index': 0, 'series': 0}}, {'kind': 'figure', 'at': 25.34, 'dur': 1.2, 'target': {'kind': 'datum', 'index': 0, 'series': 0}, 'text': '+6.8%', 'sub': 'into the print', 'color': 'pos', 'dy': -0.9}, {'kind': 'spotlight', 'at': 26.16, 'dur': 'hold', 'until': 29.12, 'target': {'kind': 'datum', 'index': 1, 'series': 0}}, {'kind': 'chart_to', 'at': 29.12, 'dur': 0.9, 'to': 'compare', 'form': 'melt', 'then': 'splash', 'hold': 'gone', 'metric': {'value': 6.8, 'text': '+6.8%', 'label': 'into the print'}, 'comparator': {'value': 3.0909, 'text': '3x', 'label': 'the gain before the news, against the gain after it'}, 'inputs': {'into': 6.8, 'after': 2.2}, 'derive': 'into / after', 'source': "[DERIVED: from the operator's backtest (EPISODE-SEEDS act three, 2026-08-30) - the mean half-month move into the print over the mean move after it, 6.8 / 2.2]"}]),
     (30.7, 41.16, 'ledger:ev-strong-prints-v1:share:0:right:built:cut;idle=live', (0, 0, 0), [('dock-f-desk-host', 0, 32.14, 41.16, {'centre': True, 'centre_x': 0.8, 'centre_y': 0.34, 'centre_w': 0.28, 'card_aspect': 0.9854})], 'cut', [{'kind': 'spotlight', 'at': 31.1, 'dur': 'hold', 'until': 36.88, 'target': {'kind': 'datum', 'index': 0, 'series': 0}}, {'kind': 'spotlight', 'at': 36.88, 'dur': 'hold', 'until': 38.2, 'target': {'kind': 'datum', 'index': 0, 'series': 0}}, {'kind': 'peel', 'at': 38.2, 'dur': 1.6}, {'kind': 'retitle', 'at': 39.7, 'dur': 1.2, 'text': 'A coin flip with drift'}]),
     (41.16, 48.42, 'ledger:ev-weak-prints-v1:bars:7:right:built:cut;idle=live', (0, 0, 0), [], 'dip', [{'kind': 'spotlight', 'at': 41.56, 'dur': 'hold', 'until': 44.32, 'target': {'kind': 'datum', 'index': 5, 'series': 0}}, {'kind': 'spotlight', 'at': 45.32, 'dur': 'hold', 'until': 46.58, 'target': {'kind': 'datum', 'index': 7, 'series': 0}}, {'kind': 'retitle', 'at': 44.32, 'dur': 1.4, 'text': 'Seven of the eight fell'}, {'kind': 'figure', 'at': 46.58, 'dur': 1.4, 'target': {'kind': 'datum', 'index': 7, 'series': 0}, 'text': 'avg −6.9%', 'sub': 'the half-month after a weak print', 'color': 'neg', 'dy': -0.9}]),
     (48.42, 57.62, 'plate-dock;idle=drift;drift=35', (0.06, 6, -4), [('dock-m-metronome', 0, 49.15, 54.0, {'arrive': 'throw', 'mass': 'paper', 'centre': True, 'centre_y': 0.38, 'card_aspect': 1.8361})], 'dip', [{'kind': 'spotlight', 'at': 48.57, 'dur': 'hold', 'until': 49.7, 'target': {'kind': 'point', 'x': 0.14, 'y': 0.8}}, {'kind': 'spotlight', 'at': 52.08, 'dur': 'hold', 'until': 55.56, 'target': {'kind': 'point', 'x': 0.42, 'y': 0.82}}, {'kind': 'spotlight', 'at': 55.56, 'dur': 'hold', 'until': 57.62, 'target': {'kind': 'point', 'x': 0.14, 'y': 0.8}}]),
     (57.62, 64.54, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/systems-and-blowups/memory-trades-the-calendar/build-oneshot-3/clips/clip-two-fingers.mp4', (0, 0, 0), [('dock-stack', 0, 59.72, 64.54)], 'dip', [{'kind': 'life', 'at': 57.62, 'dur': 6.92}]),
     (64.54, 71.444, 'plate-customs;idle=drift;drift=35', (0, 0, 0), [('dock-g-july-host', 0, 68.96, 71.444, {'centre': True, 'centre_y': 0.3, 'centre_w': 0.34, 'card_aspect': 0.7167})], 'dip', [{'kind': 'spotlight', 'at': 65.36, 'dur': 'hold', 'until': 67.82, 'target': {'kind': 'point', 'x': 0.2, 'y': 0.82}}, {'kind': 'punch', 'at': 67.82, 'dur': 1.1, 'target': {'kind': 'point', 'x': 0.2, 'y': 0.52}}, {'kind': 'spotlight', 'at': 69.56, 'dur': 'hold', 'until': 71.444, 'idle': 'live', 'target': {'kind': 'point', 'x': 0.2, 'y': 0.52}}]),
     (71.444, 77.644, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/systems-and-blowups/memory-trades-the-calendar/build-oneshot-3/clips/outro-v2.mp4', (0, 0, 0), [], 'dip', [{'kind': 'life', 'at': 71.444, 'dur': 6.2}])]
