"""Generated by build_assembly.py; source rows are hard cuts over real video clips."""
# Do not edit by hand; regenerate from production/edit.json.
W = [(0.0, 7.333333, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v11/build/clips/hook.mp4', (0, 0, 0), [], 'cut', []),
     (7.333333, 8.766665999999999, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v11/build/clips/news.mp4', (0, 0, 0), [], 'cut', []),
     (8.766667, 11.833334, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v11/build/clips/follow-up.mp4', (0, 0, 0), [], 'cut', []),
     (11.833333, 16.033333, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v11/build/clips/hendo.mp4', (0, 0, 0), [], 'cut', []),
     (16.033333, 18.633333, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v11/build/clips/hendo-replay.mp4', (0, 0, 0), [], 'cut', [])]
