from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / ".codex" / "config.toml"
START = "# BEGIN GENERATED PROJECT SKILL DISABLES"
END = "# END GENERATED PROJECT SKILL DISABLES"

ACTIVE_NAMES = {
    "agentic-tpm-and-execution",
    "ast-grep",
    "ast-grep-outline",
    "backend-patterns",
    "brand-voice",
    "comfyui",
    "competitive-platform-analysis",
    "deep-research",
    "define-goal",
    "e2e-testing",
    "elite-cro-and-marketing",
    "evidence-motion-engine",
    "exa-search",
    "frontend-patterns",
    "hyperframes",
    "hyperframes-animation",
    "hyperframes-cli",
    "hyperframes-core",
    "hyperframes-creative",
    "hyperframes-keyframes",
    "hyperframes-registry",
    "market-research",
    "modern-design-frameworks",
    "modern-seo-optimizations",
    "playwright",
    "prp-implement",
    "prp-plan",
    "prp-router",
    "prp-status",
    "remotion-to-hyperframes",
    "research",
    "script-writer",
    "scrum-master",
    "seo",
    "seo-content-writer",
    "sigmap",
    "strategic-compact",
    "taste",
    "tavily-web",
    "video-editing",
    "video-engine",
    "video-script-architect",
    "watch",
    "web-perf",
    "web-research-agent",
}

ROOTS = [
    Path.home() / ".codex" / "skills",
    Path.home() / ".agents" / "skills",
    REPO_ROOT / ".agents" / "skills",
    Path.home() / ".codex" / "plugins" / "cache",
]


def skill_name(skill_file: Path) -> str:
    source = skill_file.read_text(encoding="utf-8")
    match = re.search(
        r"^---\s*$.*?^name:\s*[\"']?([^\"'\r\n]+)[\"']?\s*$",
        source,
        flags=re.MULTILINE | re.DOTALL,
    )
    return match.group(1).strip() if match else skill_file.parent.name


def is_active(name: str, directory: Path) -> bool:
    normalized = str(directory).replace("\\", "/")
    if name.startswith("hyperframes"):
        return True
    return name in ACTIVE_NAMES or "/product-design/" in normalized


def skill_fingerprint(directory: Path) -> str:
    """Hash the complete skill folder so equal SKILL.md files do not hide richer refs."""
    digest = hashlib.sha256()
    for path in sorted(item for item in directory.rglob("*") if item.is_file()):
        digest.update(path.relative_to(directory).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def skill_richness(directory: Path) -> tuple[int, int]:
    files = [path for path in directory.rglob("*") if path.is_file()]
    return (sum(path.stat().st_size for path in files), len(files))


def source_kind(directory: Path) -> str:
    if directory.is_relative_to(REPO_ROOT / ".agents" / "skills"):
        return "project"
    if directory.is_relative_to(Path.home() / ".agents" / "skills"):
        return "shared"
    if directory.is_relative_to(Path.home() / ".codex" / "skills"):
        return "personal"
    return "plugin"


def preferred_active(name: str, candidates: list[Path]) -> Path:
    """Select one enabled copy, preserving the richest complete skill folder."""
    fingerprints = {skill_fingerprint(directory) for directory in candidates}
    identical = len(fingerprints) == 1

    if identical:
        preference = {"shared": 4, "project": 3, "personal": 2, "plugin": 1}
    else:
        preference = {"project": 4, "shared": 3, "personal": 2, "plugin": 1}

    return max(
        candidates,
        key=lambda directory: (
            (0, 0) if identical else skill_richness(directory),
            preference[source_kind(directory)],
            str(directory),
        ),
    )


def active_skills(skills: list[tuple[str, Path]]) -> list[tuple[str, Path]]:
    """Return one canonical enabled location per allowed skill name."""
    grouped: dict[str, list[Path]] = {}
    for name, directory in skills:
        if is_active(name, directory):
            grouped.setdefault(name, []).append(directory)
    return sorted(
        ((name, preferred_active(name, directories)) for name, directories in grouped.items()),
        key=lambda item: (item[0], str(item[1])),
    )


def toml_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def collect_skills() -> list[tuple[str, Path]]:
    files = {
        path.resolve()
        for root in ROOTS
        if root.exists()
        for path in root.rglob("SKILL.md")
    }
    return sorted(
        ((skill_name(path), path.parent) for path in files),
        key=lambda item: (item[0], str(item[1])),
    )


def generated_block(disabled: list[tuple[str, Path]]) -> str:
    entries = "\n\n".join(
        f"[[skills.config]]\npath = {toml_literal(str(directory))}\nenabled = false"
        for _, directory in disabled
    )
    return "\n".join(
        [
            START,
            "# Generated by scripts/configure_codex_skill_allowlist.py.",
            "# Run `python scripts/configure_codex_skill_allowlist.py --write`.",
            entries,
            END,
            "",
        ]
    )


def replace_block(config: str, block: str) -> str:
    start = config.find(START)
    if start < 0:
        return config.rstrip() + "\n\n" + block
    end = config.find(END, start)
    if end < 0:
        raise ValueError(f"found {START} without {END}")
    return config[:start].rstrip() + "\n\n" + block + config[end + len(END) :].lstrip()


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    skills = collect_skills()
    active = active_skills(skills)
    active_paths = {directory for _, directory in active}
    disabled = [item for item in skills if item[1] not in active_paths]
    current = CONFIG_PATH.read_text(encoding="utf-8")
    expected = replace_block(current, generated_block(disabled))

    ok = True
    if args.write:
        CONFIG_PATH.write_text(expected, encoding="utf-8")
    elif args.check and current != expected:
        ok = False

    print(
        json.dumps(
            {
                "ok": ok,
                "mode": "write" if args.write else "check" if args.check else "preview",
                "discovered": len(skills),
                "active": len(active),
                "disabled": len(disabled),
                "activeNames": sorted({name for name, _ in active}),
                "configPath": str(CONFIG_PATH),
            },
            indent=2,
        )
    )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
