"""Tokyo Tea Break - P58 T7, THE FIRST 2.5D CUT: a NEW short beside the approved one, never a rebuild of it (E45).

    TOKYO_BUILD_DIR=build-p58-2-5d python build_short_p58.py

It is `build_short.py` exactly - the same script, take, docks, captions, sound and kinetics - with its `shot_table()`
overridden by the T7 changes and NOTHING else:
  1. row 3's world is the LAYERED plate `world-tokyo-customs-dock-v1` (four b-sam planes in its `.layers.json`). The
     row's exit (`suck`) and life (steam / trace / ticker) stay as authored. No camera move is added: under a LOCKED
     camera a layered plate paints identical to its flat composite (T3's test) - E59 obeyed, not a defect.
  2. row 5's bars page takes `;form=extruded_bar` (T5 - the ONE 2.5D chart; the `story` builder).
  3. DROPPED: a page stands in a plate's space only as a CARD over the scene BEFORE it (the `page-depth` golden: the
     plate is scene s01, the `;card` page s02; the engine's `cardworld`). Row 6's scene before is row 5's Meta page,
     not a plate, so a depth page on the desk plate needs a restaged row 5 or a new scene - not one of the changes.
The shot table is written INSIDE the build dir; the project's `SHOT-TABLE-SHORT.py` is never touched.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

BUILD_DIR = "build-p58-2-5d"
os.environ.setdefault("TOKYO_BUILD_DIR", BUILD_DIR)
if os.environ["TOKYO_BUILD_DIR"] != BUILD_DIR:
    raise SystemExit(f"FAIL: build_short_p58 builds {BUILD_DIR} only (TOKYO_BUILD_DIR={os.environ['TOKYO_BUILD_DIR']!r})")

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import build_short as B   # noqa: E402

LAYERED_PLATE = "world-tokyo-customs-dock-v1"
FROM_PLATE = "plate-p-viewers-desk"
FORM = ";form=extruded_bar"
SHOT_TABLE_REL = f"{BUILD_DIR}/SHOT-TABLE-SHORT.py"

_live_shot_table = B.shot_table


def shot_table(ws: list[dict], runtime_s: float, t_outro: float | None = None) -> list[tuple]:
    """The live table with T7's two landed changes; refuses if the live rows moved under it."""
    rows = [list(r) for r in _live_shot_table(ws, runtime_s, t_outro)]
    if len(rows) != 7:
        raise SystemExit(f"FAIL: the live table has {len(rows)} rows, T7 was authored on 7")
    if rows[2][2] != FROM_PLATE:
        raise SystemExit(f"FAIL: row 3's world is {rows[2][2]!r}, expected {FROM_PLATE!r}")
    if not str(rows[4][2]).startswith("ledger:ev-meta-yield-v1:bars:"):
        raise SystemExit(f"FAIL: row 5's world is {rows[4][2]!r}, expected the Meta bars page")
    rows[2][2] = LAYERED_PLATE
    rows[4][2] = rows[4][2] + FORM
    return [tuple(r) for r in rows]


def main() -> int:
    live_write, live_compile = B.T.write_shot_table, B.T.compile_timeline

    def write_shot_table(path: Path, rows: list[tuple], header: str) -> Path:
        return live_write(B.BUILD / "SHOT-TABLE-SHORT.py", rows,
                          '"""Tokyo short - P58 T7 2.5D cut, GENERATED by build_short_p58.py. Do not hand-edit."""\n')

    def compile_timeline(*args, **kwargs) -> int:
        kwargs["shot_table_file"] = SHOT_TABLE_REL
        return live_compile(*args, **kwargs)

    live_cues = B.sound_cues

    def sound_cues(rows: list[tuple]) -> list[dict]:
        # the kit reads a page's cut as `plate_id.endswith(":cut")` (authoring/audio.py:99), so `;form=` after `:cut` would
        # add a flip-retract cue to a page that never retracts - the sound map is the approved cut's, read without the form
        return live_cues([(*r[:2], str(r[2]).replace(FORM, ""), *r[3:]) for r in rows])

    B.shot_table = shot_table
    B.sound_cues = sound_cues
    B.T.write_shot_table = write_shot_table
    B.T.compile_timeline = compile_timeline
    return B.main()


if __name__ == "__main__":
    raise SystemExit(main())
