"""Generated by build_assembly.py; source rows are hard cuts over real video clips."""
# Do not edit by hand; regenerate from production/edit.json.
W = [(0.0, 6.166667, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v10/build/clips/hook.mp4', (0, 0, 0), [], 'cut', []),
     (6.166667, 7.6000000000000005, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v10/build/clips/news.mp4', (0, 0, 0), [], 'cut', []),
     (7.6, 7.8999999999999995, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v10/build/clips/left-hook-lead.mp4', (0, 0, 0), [], 'cut', []),
     (7.9, 11.066667, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v10/build/clips/first-left-impact.mp4', (0, 0, 0), [], 'cut', []),
     (11.066667, 15.266667000000002, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v10/build/clips/hendo.mp4', (0, 0, 0), [], 'cut', []),
     (15.266667, 17.866667, 'clip:C:/Users/Snipe/Downloads/Outreach Program/content/video_engine/projects/martial-matters/pilots/knockout-brain-matchcut-001/production/assembly-v10/build/clips/hendo-replay.mp4', (0, 0, 0), [], 'cut', [])]
